"""add items and card_number to orders

Revision ID: 1de22c88711b
Revises: 774751d45a9e
Create Date: 2026-09-03 03:09:28.006655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de22c88711b'
down_revision: Union[str, Sequence[str], None] = '774751d45a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('items', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('card_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'card_number')
    op.drop_column('orders', 'items')
    # ### end Alembic commands ###
