"""add created_at, went_to_dlq to orders table

Revision ID: 4f948dd051a8
Revises: 1de22c88711b
Create Date: 2026-09-03 11:31:11.074246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f948dd051a8'
down_revision: Union[str, Sequence[str], None] = '1de22c88711b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('orders', sa.Column('went_to_dlq', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'went_to_dlq')
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
