"""create products table

Revision ID: d8209a3fbef5
Revises: 
Create Date: 2026-08-31 04:30:13.009840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8209a3fbef5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        sa.table(
            "products",
            sa.column("id", sa.Uuid(as_uuid=False)),
            sa.column("product_name", sa.String()),
            sa.column("stock", sa.Integer()),
        ),
        [
            {"id": "11111111-1111-1111-1111-111111111111", "product_name": "한정판 스니커즈", "stock": 1},
            {"id": "22222222-2222-2222-2222-222222222222", "product_name": "기본 티셔츠", "stock": 999},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
